ignore-failures:
  python:
    # UNHEALTHY AND USED IN PRODUCTION
    - accept-types
    - brotli
    - html2text
    - python-geoip-geolite2-yplan
    - python-geoip-yplan

    # unhealthy, but not used in production
    - astor             # required by flake8-scream and flake8-simplify
    - autoflake         # used in GitHub Actions
    - funcparserlib     # required by hy
    - html5lib          # used by the tests
    - iniconfig         # required by pytest
    - mypy-extensions   # required by black and mypy
    - pylint-pytest
    - pyrepl            # used by the backdoor client
    - pysocks           # used by the backdoor client
    - pytest-tornasync  # used by the tests
    - toml              # required by dparse and pre-commit
    - webencodings      # required by html5lib
