repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
      - id: requirements-txt-fixer
        files: ^requirements.*\.txt$
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
      - id: insert-license
        files: ^.+\.py$
        args:
          - --license-filepath
          - license_header.txt          # defaults to: LICENSE.txt
      #- id: insert-license
      #  files: \*\.css$
      #  args:
      #    - --license-filepath
      #    - license_header.txt          # defaults to: LICENSE.txt
      #    - --comment-style
      #    - /*| *| */                   # defaults to: #
      #- id: insert-license
      #  files: \*\.html$
      #  args:
      #    - --license-filepath
      #    - license_header.txt          # defaults to: LICENSE.txt
      #    - --comment-style
      #    - '{#||#}'                    # defaults to: #
