[tool.black]
line-length = 79
target-version = ["py39"]

[tool.isort]
atomic = true
profile = "black"
py_version = "39"
line_length = 79
skip_gitignore = true
#add_imports = ["from __future__ import annotations, barry_as_FLUFL"]

[tool.mypy]
python_version = 3.9
show_column_numbers = true
show_error_codes = true
