[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
atomic = true
profile = "black"
py_version = "310"
line_length = 79
skip_gitignore = true
add_imports = ["from __future__ import annotations"]

[tool.mypy]
python_version = "3.10"
show_column_numbers = true
show_error_codes = true
warn_unreachable = true
strict_equality = true
no_implicit_reexport = true
#no_implicit_optional = true
#disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
