[tool.black]
line-length = 80
target-version = ["py310"]

[tool.isort]
atomic = true
profile = "black"
py_version = "310"
line_length = 80
skip_gitignore = true
add_imports = ["from __future__ import annotations"]

[tool.mypy]
strict = true
python_version = "3.10"
warn_unreachable = true
show_error_codes = true
show_column_numbers = true
plugins = "numpy.typing.mypy_plugin"
