name: Check
on:
  push:
    paths:
      - "tests/**"
      - "an_website/**"
      - ".github/workflows/check.yml"
      - "requirements.txt"
      - "pyproject.toml"
      - ".mypy.ini"
      - ".pylintrc"
  pull_request:
    paths:
      - "tests/**"
      - "an_website/**"
      - ".github/workflows/check.yml"
      - "requirements.txt"
      - "pyproject.toml"
      - ".mypy.ini"
      - ".pylintrc"

jobs:

  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install Black and isort
        run: grep -E "^(black|isort|rjsmin)" requirements-dev.txt | xargs pip install --prefer-binary
      - name: Run isort
        run: isort .
      - name: Run Black
        run: black .
      - name: Minify JS files
        run: python3 minify_js.py
      - name: Minify CSS files
        run: python3 minify_css.py
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤦"

  check_types:
    name: Check types
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache type information
        uses: pat-s/always-upload-cache@v2
        with:
          path: .mypy_cache
          key: mypy-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: mypy-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-
      - name: Install libcurl4-openssl-dev for compiling PycURL
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Install requirements
        run: grep -v "^[#]" requirements.txt | xargs pip install --prefer-binary
      - name: Install mypy
        run: grep -E "^mypy" requirements-dev.txt | xargs pip install --prefer-binary
      - name: Install types in check-requrements.txt
        run: grep -E "^types-" requirements-dev.txt | xargs pip install --prefer-binary
      - name: Run mypy
        run: mypy --no-warn-unused-ignores --no-warn-redundant-casts -p an_website

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache collected data
        uses: pat-s/always-upload-cache@v2
        with:
          path: ~/.cache/pylint
          key: pylint-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: pylint-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-
      - name: Install libcurl4-openssl-dev for compiling PycURL
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Install requirements
        run: grep -v "^[#]" requirements.txt | xargs pip install --prefer-binary
      - name: Install Flake8 and Pylint
        run: grep -E "^(flake8|pylint)" requirements-dev.txt | xargs pip install --prefer-binary
      - name: Run Flake8
        run: flake8 --extend-ignore=D100,D101,D102,D103,D104,E501
      - name: Run Pylint
        run: pylint -d fixme an_website
