name: Check
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache collected data
        uses: pat-s/always-upload-cache@v2
        with:
          path: ~/.pylint.d
          key: pylint-${{ github.sha }}
          restore-keys: pylint-
      - name: Install requirements
        run: |
          cat requirements.txt | grep -v "pycurl*" | xargs pip install --user
      - name: Install Pylint
        run: |
          pip install --user "pylint<3.0"
      - name: Run Pylint
        run: |
          pylint --output-format=colorized -d R an_website
  check_formatting:
    name: Check formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          cat requirements.txt | grep -v "pycurl*" | xargs pip install --user
      - name: Install Black
        run: |
          pip install --user "black"
      - name: Run Black
        run: |
          git ls-files "*.py" | xargs black --check --diff --color -t py38 -l 100
  check_types:
    name: Check types
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache type information
        uses: pat-s/always-upload-cache@v2
        with:
          path: .mypy_cache
          key: mypy-${{ github.sha }}
          restore-keys: mypy-
      - name: Install requirements
        run: |
          cat requirements.txt | grep -v "pycurl*" | xargs pip install --user
      - name: Install mypy
        run: |
          pip install --user "mypy<2.0"
      - name: Run mypy
        run: |
          mypy --show-column-numbers --show-error-codes -p an_website
