name: Check
on: [push, pull_request, pull_request_target]

jobs:
  check_formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install Black and isort
        run: |
          pip install --user black "isort<6"
      - name: Run Black
        run: |
          black -t py38 .
      - name: Run isort
        run: |
          isort .
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: fix formatting
  check_types:
    name: Check types
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - 3.10
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache type information
        uses: pat-s/always-upload-cache@v2
        with:
          path: .mypy_cache
          key: mypy-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: mypy-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-
      - name: Install requirements
        run: |
          grep -v "^[#]" requirements.txt | grep -v "pycurl*" | xargs pip install --user
      - name: Install type stubs
        run: |
          pip install --user types-orjson
      - name: Install mypy
        run: |
          pip install --user "mypy<2"
      - name: Run mypy
        run: |
          mypy -p an_website
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
          - 3.10
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache collected data
        uses: pat-s/always-upload-cache@v2
        with:
          path: ~/.pylint.d
          key: pylint-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: pylint-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-
      - name: Install requirements
        run: |
          grep -v "^[#]" requirements.txt | grep -v "pycurl*" | xargs pip install --user
      - name: Install Pylint
        run: |
          pip install --user "pylint<3"
      - name: Run Pylint
        run: |
          pylint -d line-too-long an_website
