name: Check
on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache results
        uses: actions/cache@v2
        with:
          path: ~/.pylint.d
          key: ${{ runner.os }}-${{ hashFiles('~/.pylint.d/*') }}
      - name: Install requirements
        run: |
          pip install --user -r requirements.txt
      - name: Install Pylint
        run: |
          pip install --user "pylint>=2.8.3,<3.0"
      - name: Run Pylint
        run: |
          pylint --output-format=colorized -d all -e W,E,F -d python3 an_website
  check_types:
    name: Check types
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache results
        uses: actions/cache@v2
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-${{ hashFiles('.mypy_cache/*') }}
      - name: Install requirements
        run: |
          pip install --user -r requirements.txt
      - name: Install mypy
        run: |
          pip install --user "mypy<2.0"
      - name: Run mypy
        run: |
          mypy --show-column-numbers --show-error-codes -p an_website
