name: Check
on:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache results
        uses: actions/cache@v2
        with:
          path: ~/.pylint.d
          key: ${{ runner.os }}-${{ hashFiles('~/.pylint.d/*') }}
      - name: Install requirements
        run: |
          pip install --user -r requirements.txt
      - name: Install Pylint
        run: |
          pip install --user pylint>=2.8.3,<3.0
      - name: Run Pylint
        continue-on-error: true
        run: |
          git ls-files "*.py" | xargs pylint --output-format=colorized
  check_types:
    name: Check types
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache results
        uses: actions/cache@v2
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-${{ hashFiles('.mypy_cache/*') }}
      - name: Install requirements
        run: |
          python3 -m venv venv
          venv/bin/pip install -r requirements.txt
      - name: Install mypy
        run: |
           venv/bin/pip install mypy<2.0
      - name: Run mypy
        continue-on-error: true
        run: |
          MYPYPATH=".,venv/lib/python3.9/site-packages/,venv/lib64/python3.9/site-packages/" git ls-files "*.py" | grep -v "gen_words.py" | grep -v "replace_umlauts.py" |  xargs venv/bin/mypy --show-column-numbers --show-error-codes --namespace-packages --explicit-package-base

