name: Check
on:
  push:
    branches: [ "**" ]
  pull_request:
env:
  PIP_DISABLE_PIP_VERSION_CHECK: yes

jobs:

  fix_stupid_mistakes:
    name: Fix stupid mistakes
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt
      - name: Install required stuff
        run: grep -E "^(autoflake|black|isort|rcssmin|regex|rjsmin)" requirements-ci.txt | xargs pip install
      - name: Run autoflake
        run: autoflake --recursive --in-place --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables .
      - name: Run isort
        run: isort .
      - name: Run Black
        run: black .
      - name: Minify JS files
        run: ./scripts/minify_js.py --clean
      - name: Minify CSS files
        run: ./scripts/minify_css.py --clean
      - name: Generate humans.txt
        run: ./scripts/humans.py
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤦"

  check_types:
    name: Check types
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt
      - name: Cache type information
        uses: pat-s/always-upload-cache@v2
        with:
          path: .mypy_cache
          key: mypy-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: mypy-${{ github.repository }}-${{ github.ref }}-
      - name: Install libcurl4-openssl-dev for compiling PycURL
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install mypy + stuff required for checking the tests
        run: grep -E "^(html5lib|mypy|pytest|types-)" requirements-ci.txt | xargs pip install
      - name: Run mypy
        run: mypy -p an_website -p tests -p scripts

  flake8:
    name: Flake8
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt
      - name: Install libcurl4-openssl-dev for compiling PycURL
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install Flake8 + stuff required for checking the tests
        run: grep -E "^(flake8|html5lib|pep8-naming|pytest)" requirements-ci.txt | xargs pip install
      - name: Run Flake8
        run: flake8

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt
      - name: Cache collected data
        uses: pat-s/always-upload-cache@v2
        with:
          path: ~/.cache/pylint
          key: pylint-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: pylint-${{ github.repository }}-${{ github.ref }}-
      - name: Install libcurl4-openssl-dev for compiling PycURL
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install Pylint + stuff required for checking the tests
        run: grep -E "^(html5lib|pylint|pytest|rcssmin|rjsmin)" requirements-ci.txt | xargs pip install
      - name: Run Pylint
        run: pylint -d fixme setup.py an_website tests scripts
