name: Deploy
on:
  push:
    branches: [main]
    paths:
      - "an_website/**"
      - ".github/workflows/deploy.yml"
      #- "requirements.txt"
      #- "an_website.ini"
      #- "restart.sh"
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  check:
    name: Check for errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Pyflakes
        run: |
          pip install "pyflakes<3"
      - name: Run Pyflakes
        run: |
          pyflakes an_website
  hash_files:
    name: Hash files
    runs-on: ubuntu-latest
    needs: check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Hash files
        run: |
          mkdir public
          echo "Hash der Datei-Hashes:" > public/version.txt
          sh -c "cd an_website && git ls-files | xargs sha1sum | sha1sum | cut -d ' ' -f 1" >> public/version.txt
          echo >> public/version.txt
          echo "Datei-Hashes:" >> public/version.txt
          sh -c "cd an_website && git ls-files | xargs sha1sum" >> public/version.txt
      - name: Upload as Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: public/version.txt
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - check
      - hash_files
    steps:
      - name: Publish Changes
        run: |
          curl -H "Authorization: ${{ secrets.API_RESTART_SECRET }}" \
            https://joshix.asozial.org/restart?commit=${{ github.event.head_commit.message }}
