name: Deploy
on:
  push:
    branches: [main]

jobs:
  check:
    name: Check for errors
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          cat requirements.txt | grep -v "pycurl*" | xargs pip install --user
      - name: Install Pyflakes
        run: |
          pip install --user "pyflakes<3"
      - name: Run Pyflakes
        run: |
          pyflakes an_website
  hash_files:
    name: Hash files
    runs-on: ubuntu-20.04
    needs: check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Hash files
        run: |
          mkdir hash_file_folder
          echo "Hash der Datei-Hashes:" > hash_file_folder/version.txt
          sh -c "git ls-files an_website | xargs sha1sum | sha1sum | cut -d ' ' -f 1 >> hash_file_folder/version.txt"
          echo >> hash_file_folder/version.txt
          echo "Datei-Hashes:" >> hash_file_folder/version.txt
          sh -c "git ls-files an_website | xargs sha1sum >> hash_file_folder/version.txt"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: hash_file_folder
