name: Deploy stuff
on:
  push:
    branches: [main]
    paths:
      - "test/**"
      - "an_website/**"
      - ".github/workflows/deploy.yml"
      - "requirements.txt"
      - "an_website.ini"
      - "update.sh"
concurrency:
  group: deploy
  cancel-in-progress: true

jobs:

  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install libcurl4-openssl-dev for compiling PycURL
        run: sudo apt-get install -y libcurl4-openssl-dev
      - name: Install requirements
        run: grep -E -v "^(#|-i|pip)" requirements.txt | xargs pip install --prefer-binary
      - name: Install pytest, coverage and html5lib (needed for the tests)
        run: grep -E "^(pytest|coverage|html5lib)" requirements-dev.txt | xargs pip install --prefer-binary
      - name: Run pytest
        run: pytest --cov=an_website test
      - name: Upload coverage as Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: .coverage
          name: coverage

  hash_files:
    name: Hash files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install b3sum
        run: cargo install b3sum
      - name: Hash files
        run: |
          mkdir -p public
          echo "Hash der Datei-Hashes:" > public/version.txt
          sh -c "cd an_website && git ls-files | xargs b3sum | b3sum | cut -d ' ' -f 1" >> public/version.txt
          echo >> public/version.txt
          echo "Datei-Hashes:" >> public/version.txt
          sh -c "cd an_website && git ls-files | xargs b3sum" >> public/version.txt
      - name: Upload as Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: public/
          name: version

  gh_pages:
    name: Push version and coverage to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - run_tests
      - hash_files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Download coverage
        uses: actions/download-artifact@v3
        with:
          name: coverage
      - name: Download version
        uses: actions/download-artifact@v3
        with:
          name: version
      - name: Move files
        run: |
          mkdir -p public
          mv version.txt public/
      - name: Create coverage files
        run: |
          grep "^coverage" requirements-dev.txt | xargs pip install --prefer-binary
          coverage html -d "public/coverage"
          coverage json -o "public/coverage.json"
          set -x
          # get the total percentage covered and round it to 2 decimals:
          total="$(jq '.totals.percent_covered' public/coverage.json | awk '{ printf( "%3.2f\n", $1 ) }')"
          if (( $(echo "$total <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$total > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi
          curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > public/coverage/badge.svg
          rm public/coverage/.gitignore
      - name: Push version and coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}

  deploy_website:
    name: Deploy website
    runs-on: ubuntu-latest
    needs:
      - gh_pages
    steps:
      - name: Deploy website
        run: |
          POST -f -H "Authorization: ${{ secrets.API_RESTART_SECRET }}" \
            https://asozial.org/api/restart?commit=${{ github.event.head_commit.id }}
