name: Deploy
on:
  push:
    branches: [main]

jobs:
  #lint:
  #  name: Check for errors
  #  runs-on: ubuntu-20.04
  #  steps:
  #    - name: Checkout repository
  #      uses: actions/checkout@v2
  #    - name: Install requirements
  #      run: |
  #        pip install --user -r requirements.txt
  #    - name: Install Pylint
  #      run: |
  #        pip install --user pylint>=2.8.3,<3.0
  #    - name: Run Pylint
  #      run: |
  #        git ls-files "*.py" | xargs pylint --persistent=no --errors-only --output-format=colorized
  hash_files:
    name: Hash files
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Hash files
        run: |
          mkdir hash_file_folder
          echo "Hash der Datei-Hashes:" > hash_file_folder/version.txt
          sh -c "git ls-files | xargs sha1sum | sha1sum | cut -d ' ' -f 1 >> hash_file_folder/version.txt"
          echo >> hash_file_folder/version.txt
          echo "Datei-Hashes:" >> hash_file_folder/version.txt
          sh -c "git ls-files | xargs sha1sum >> hash_file_folder/version.txt"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: hash_file_folder
