name: Deploy
on:
  push:
    branches: [main]
    paths:
      - "tests/**"
      - "an_website/**"
      - ".github/workflows/deploy.yml"
      - "requirements.txt"
      - "an_website.ini"
      - "restart.sh"
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  check:
    name: Check for errors
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Pyflakes
        run: |
          pip install "pyflakes<3"
      - name: Run Pyflakes
        run: |
          pyflakes an_website

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install requirements
        run: |
          grep -v "^[#]" requirements.txt | grep -v "pycurl*" | xargs pip install --prefer-binary
      - name: Install pytest and coverage
        run: |
          pip install pytest~=6.2.5 coverage~=5.5
      - name: Run pytest
        run: |
          coverage run --source=an_website -m py.test tests/
      - name: Create coverage files
        run: |
          coverage html -d "public/coverage"
          coverage json -o "coverage.json"
      - name: Upload coverage as Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: public/
          name: coverage

  hash_files:
    name: Hash files
    runs-on: ubuntu-latest
    needs:
      - check
      - test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Hash files
        run: |
          mkdir -p public
          echo "Hash der Datei-Hashes:" > public/version.txt
          sh -c "cd an_website && git ls-files | xargs sha1sum | sha1sum | cut -d ' ' -f 1" >> public/version.txt
          echo >> public/version.txt
          echo "Datei-Hashes:" >> public/version.txt
          sh -c "cd an_website && git ls-files | xargs sha1sum" >> public/version.txt
      - name: Upload as Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: public/
          name: version

  deploy_github_page:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - check
      - test
      - hash_files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download coverage
        uses: actions/download-artifact@v2
        with:
          name: coverage
      - name: Download version
        uses: actions/download-artifact@v2
        with:
          name: version
      - name: Move files
        run: |
          mkdir -p public
          mv coverage public/coverage/
          mv coverage.json public/
          mv version.txt public/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - check
      - hash_files
      - test
    steps:
      - name: Publish Changes
        run: |
          POST -f -H "Authorization: ${{ secrets.API_RESTART_SECRET }}" \
            https://joshix.asozial.org/restart?commit=${{ github.event.head_commit.id }}
