name: Deploy
on:
  push:
    branches: [main]

jobs:
  check:
    name: Check for errors
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      #- name: Install requirements
      #  run: |
      #    grep -v "^[#]" requirements.txt | grep -v "pycurl*" | xargs pip install --user
      - name: Install Pyflakes
        run: |
          pip install --user "pyflakes<3"
      - name: Run Pyflakes
        run: |
          pyflakes an_website
  hash_files:
    name: Hash files
    runs-on: ubuntu-20.04
    needs: check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Hash files
        run: |
          mkdir public
          echo "Hash der Datei-Hashes:" > public/version.txt
          sh -c "cd an_website && git ls-files | xargs sha1sum | sha1sum | cut -d ' ' -f 1" >> public/version.txt
          echo >> public/version.txt
          echo "Datei-Hashes:" >> public/version.txt
          sh -c "cd an_website && git ls-files | xargs sha1sum" >> public/version.txt
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
      - name: Upload as Build Artifact
        uses: actions/upload-artifact@v2
        with:
          path: public/version.txt
