name: Check emoji
on: [ push, pull_request ]
jobs:
  check_emoji:
    name: Look for Emoji in commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install required library
        run: python3 -m pip install --prefer-binary "emoji>=1.6.3"
      - name: Run the check
        shell: python
        run: |
          import os
          import emoji
          if "${{ github.event_name }}".startswith("pull_request"):
              print(os.popen("git fetch").read())
              commit = "${{ github.event.after }}"
          else:
              commit = "${{ github.sha }}"
          commit_message = os.popen(f"git show -s --format=%B {commit}").read()
          if not emoji.emoji_count(commit_message):
            exit("No Emoji found. 👎")
