name: Check emoji
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  check_emoji:
    name: Look for emoji in commit message
    runs-on: ubuntu-latest
    steps:
      - name: Run the check
        run: exit $(python3 -c  "import unicodedata;print(0 if 'S' in tuple(unicodedata.category(ch)[0] for ch in '${{ github.event.commits[0].message }}') else 1)")
