name: Check emoji
on: [ push, pull_request ]
jobs:
  check_emoji:
    name: Look for Emoji in commit message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install required library
        run: python3 -m pip install --prefer-binary "emoji>=1.6.1"
      - name: Run the check
        shell: python
        run: |
          import os
          import emoji
          commit_message = os.popen("git show -s --format=%B ${{ github.sha }}").read()
          if not emoji.emoji_count(commit_message):
            exit("No Emoji found. 👎")
