name: Hash Files
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: hash files
        run: |
          mkdir hash_file_folder
          sh -c "git ls-files | xargs sha1sum > hash_file_folder/version.txt"
          echo >> hash_file_folder/version.txt
          sh -c "git ls-files | xargs sha1sum | sha1sum | cut -d ' ' -f 1 >> hash_file_folder/version.txt"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: hash_file_folder
