name: Check PR
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: hash files
        run: |
          cat .github/workflows/hash_files.yml
          echo
          sh -c "git ls-files | xargs sha256sum"
          echo
          sh -c "git ls-files | xargs sha256sum | sha256sum | cut -d ' ' -f 1"
