name: Release
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    tags: [ v* ]
env:
  PIP_DISABLE_PIP_VERSION_CHECK: yes

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Fetch tags
        if: github.event_name == 'schedule'
        run: git fetch --tags
      - name: Check if already released
        if: github.event_name == 'schedule'
        run: test -z $(git tag --list "v*" --points-at)
      - name: Create tag
        if: github.event_name == 'schedule'
        run: git tag $(python -c "from time import strftime, gmtime; print(strftime('v%y.%m.%d', gmtime()))")
      - name: Push tag
        if: github.event_name == 'schedule'
        run: git push --tags
      - name: Install build frontend
        run: pip install "build>=0.8,<2"
      - name: Build
        run: python -m build
      - name: Upload as build artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          #- 3.11
          #- 3.12
        stack-version:
          - 7.17.5
          #- 8.3.2
        #license:
        #  - basic
        #  - trial
    services:
      redis:
        image: redis/redis-stack-server:6.2.2-v5
        ports:
          - 6379:6379
    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Start Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ matrix.stack-version }}
          security-enabled: false
          nodes: 3
          #license: ${{ matrix.license }}
          plugins: |
            analysis-icu
            analysis-phonetic
            ingest-attachment
            mapper-size
            mapper-murmur3
            mapper-annotated-text
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements*.txt
      - name: Install libcurl4-openssl-dev for compiling PycURL
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install stuff needed for the tests
        run: grep -E "^(coverage|html5lib|pytest)" requirements-ci.txt | xargs pip install
      - name: Run pytest
        run: pytest --durations=0 --verbose --cov=an_website --cov-config=.coveragerc tests
      - name: Upload coverage as artifact
        uses: actions/upload-artifact@v3
        with:
          path: .coverage
          name: coverage

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - build
      - tests
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - id: version
        shell: python
        run: |
          from time import strftime, gmtime
          if "${{ github.event_name }}" == "schedule":
            print(f"::set-output name=VERSION::{strftime('v%y.%m.%d', gmtime())}")
          elif "${{ github.event_name }}" == "push" and "${{ github.ref_type }}" == "tag":
            print("::set-output name=VERSION::${{ github.ref_name }}")
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          generate_release_notes: true
          files: |
            *.tar.gz
            *.whl

  pypi:
    name: Upload to PyPI
    runs-on: ubuntu-latest
    needs:
      - build
      - tests
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Install Twine
        run: pip install "twine==4.*"
      - name: Run Twine
        run: |
          twine check --strict *.tar.gz *.whl
          twine upload --verbose --disable-progress-bar *.tar.gz *.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  sourcemaps:
    name: Upload sourcemaps
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    needs:
      - build
      - tests
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - id: version
        shell: python
        run: |
          from os import popen as run
          from packaging.utils import parse_sdist_filename
          filename = run("ls an-website-*.tar.gz").read().strip()
          ver = parse_sdist_filename(filename)[1])
          print(f"::set-output name=VERSION::{ver}")
      - name: Unpack source distribution
        run: tar xvf an-website-*.tar.gz
      - name: Upload sourcemaps
        run: |
          cd an-website-*/an_website/static/js
          find static/js -type f -name "*.js" -exec \
            curl http://apm.asozial.org:8200/assets/v1/sourcemaps \
              -H "Authorization: Bearer ${{ secrets.APM_TOKEN }}" \
              -F service_name="an-website" \
              -F service_version="${{ steps.version.outputs.VERSION }}" \
              -F bundle_filepath="/{}" \
              -F sourcemap=@{}.map \;

  deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    needs:
      - build
      - tests
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Deploy website
        run: |
          curl -sSf -T *.whl https://asozial.org/api/update/ \
            -H "Authorization: ${{ secrets.UPDATE_API_SECRET }}"

  hashes:
    name: Hash files
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Hash files
        run: ./scripts/hash_files.py > hashes
      - name: Upload as build artifact
        uses: actions/upload-artifact@v3
        with:
          path: hashes
          name: hashes

  gh_pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    needs:
      - deploy
      - hashes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements*.txt
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Move files
        run: |
          mkdir public
          mv hashes/hashes public/hashes.txt
          mv coverage/.coverage .
      - name: Create coverage files
        run: |
          grep "^coverage" requirements-ci.txt | xargs pip install
          coverage report --precision=3 --sort=-miss --skip-covered
          coverage html -d "public/coverage"
          coverage json -o "public/coverage.json"
          set -x
          ./generate-badge.sh > public/coverage/badge.svg
          rm public/coverage/.gitignore
      - name: Push hashes and coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}
