name: Test
on:
  push:
    paths:
      - "an_website/**"
      - "tests/**"
      - ".github/workflows/check.yml"
      - "requirements.txt"
      - "pyproject.toml"
  pull_request:
    paths:
      - "an_website/**"
      - "tests/**"
      - ".github/workflows/check.yml"
      - "requirements.txt"
      - "pyproject.toml"
  pull_request_target:
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10.0-alpha - 3.10.0"
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache type information
        uses: pat-s/always-upload-cache@v2
        with:
          path: .pytest_cache
          key: pytest-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: pytest-${{ matrix.python-version }}-${{ github.repository }}-${{ github.ref }}-
      - name: Install build requirements for orjson (temporary fix)
        if: matrix.python-version == '3.10.0-alpha - 3.10.0'
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-2021-05-25 --profile minimal -y
          pip install maturin
      - name: Install requirements
        run: |
          grep -v "^[#]" requirements.txt | grep -v "pycurl*" | xargs pip install --prefer-binary
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run pytest
        run: |
          py.test tests/
